"""contract — the consumer-contract manifest + assumption lint (#584).

Two layers:
  - REAL-TREE tests against this repo's own templates/ + CI surfaces — they
    pin the contract anchors (the bootstrap quartet, the gate-internal set),
    determinism, the committed manifest's freshness, and that the lint passes
    CLEAN on today's tree (the shrink-only baseline was drained to zero and
    its file deleted in #588).
  - SYNTHETIC tests in tmp repos — drift detection, the #579-shape violation
    (managed-path reference, no materialize), step ordering, the composite
    pseudo-job, the checkout-provider rule, the path boundary, and the
    baseline ratchet (grandfather + stale-entry failure).

yq is required (yamlio parses the workflow YAML through it), same as the rest
of the suite.
"""

from __future__ import annotations

import os
import stat
from pathlib import Path

import pytest
from release_core import contract, sync
from release_core.verbs import contract as contract_verb

# templates/commons/lib/release_core/tests/… → five levels up is the repo root.
REPO_ROOT = str(Path(__file__).resolve().parents[5])


# ── Real tree: manifest generation ────────────────────────────────────────────


def test_manifest_is_deterministic():
    assert contract.manifest_text(REPO_ROOT) == contract.manifest_text(REPO_ROOT)


def test_manifest_contains_the_contract_anchors():
    data = contract.build_manifest(REPO_ROOT)
    # The bootstrap quartet, verbatim from sync.py (sorted).
    assert data["tracked_real_files"]["bootstrap"] == sorted(sync.BOOTSTRAP_REAL_FILES)
    # The gate-internal set, verbatim from sync.py (sorted).
    assert data["gate_internal"] == sorted(sync.GATE_INTERNAL_FILES)
    # The .github/workflows real-copy rule produces the shipped workflow copy.
    assert ".github/workflows/copilot-review.yml" in data["tracked_real_files"]["workflow_copies"]
    # The ephemeral build dir.
    assert data["gitignored"] == [".release/"]
    # The #579 family is mirror dests (untracked post-WS7), never tracked files.
    mirrors = data["untracked_mirrors"]
    assert "bin/check" in mirrors
    assert "bin/check-e2e" in mirrors
    # The distributed PR-loop skill rides the mirror list.
    assert ".claude/skills/gh-pr-review-loop/SKILL.md" in mirrors
    # Managed-path prefixes are the lint's spine.
    assert data["managed_path_prefixes"] == [".release/", "bin/check", "lib/release_core/"]
    # Tombstones come from the retired sets, not a re-statement.
    assert data["tombstones"]["blob"] == sorted(sync.RETIRED_BLOB_FILES)
    assert data["tombstones"]["marker"] == sorted(sync.RETIRED_MARKER_FILES)
    assert data["tombstones"]["fingerprint"] == sorted(sync.RETIRED_FINGERPRINT_FILES)


def test_manifest_never_lists_release_internal_or_skipped_sources():
    data = contract.build_manifest(REPO_ROOT)
    listed = (
        data["tracked_real_files"]["bootstrap"]
        + data["tracked_real_files"]["workflow_copies"]
        + data["untracked_mirrors"]
    )
    for dest in listed:
        assert not sync.is_release_internal(dest), dest
        assert not dest.startswith("lib/release_core/"), dest
    # The lefthook fragments / kind manifests are sync inputs, never dests.
    assert not any(d.endswith("lefthook.fragment.yaml") for d in listed)
    assert not any(d == "manifest.yaml" for d in listed)


def test_committed_manifest_is_current():
    """The gate's freshness rule, asserted in pytest too: a PR that changes the
    contract regenerates docs/references/consumer-contract.yaml in the SAME PR."""
    committed = Path(REPO_ROOT, contract.MANIFEST_RELPATH).read_text(encoding="utf-8")
    assert committed == contract.manifest_text(REPO_ROOT), (
        "consumer-contract.yaml drifted — run: release-core admin contract dump"
    )


def test_manifest_has_no_volatile_provenance():
    text = contract.manifest_text(REPO_ROOT)
    # Byte-stability contract: no timestamps, no commit SHAs — schema field only.
    assert "contract_schema: 1" in text
    for needle in ("generated_at", "timestamp", "sha:", "Generated by release from"):
        assert needle not in text, needle


# ── Real tree: the assumption lint passes today (post-#579) ──────────────────


def test_lint_passes_on_todays_tree_with_zero_baseline():
    """Post-#588 the baseline is drained: the sweep itself is clean, no
    grandfathered jobs. A new violation OR a re-grown baseline fails here."""
    manifest = contract.build_manifest(REPO_ROOT)
    violations = contract.lint_repo(REPO_ROOT, manifest)
    assert violations == [], violations
    # The baseline FILE was deleted with the last entry (#588) — a missing
    # file is an empty baseline, and the ratchet only shrinks.
    assert not Path(REPO_ROOT, contract.BASELINE_RELPATH).exists(), (
        "the consumer-contract lint baseline was drained to zero in release#588 "
        "— do not re-create it; normalize the workflow instead"
    )
    assert contract.load_baseline(REPO_ROOT) == []


def test_rust_ci_e2e_job_is_clean_post_579():
    """The motivating breaker: rust-ci.yml's e2e job references bin/check-e2e —
    legal ONLY because #579 put the arm-gate materialize before it."""
    manifest = contract.build_manifest(REPO_ROOT)
    regex = contract._reference_regex(contract.managed_path_patterns(manifest))
    assert contract.lint_file(REPO_ROOT, ".github/workflows/rust-ci.yml", regex) == []


# ── Synthetic: dump / check drift ─────────────────────────────────────────────


@pytest.fixture
def synthetic_repo(tmp_path):
    """A minimal release-shaped tree: one commons mirror tool, one bootstrap
    real file, one kind with a shipped workflow copy."""
    root = tmp_path / "repo"
    commons_bin = root / "templates" / "commons" / "bin"
    commons_bin.mkdir(parents=True)
    (commons_bin / "check-gate").write_text("#!/bin/sh\nexit 0\n")
    (commons_bin / "check-gate").chmod((commons_bin / "check-gate").stat().st_mode | stat.S_IXUSR)
    (commons_bin / "install-release-core").write_text("#!/bin/sh\nexit 0\n")
    wf = root / "templates" / "mykind" / ".github" / "workflows"
    wf.mkdir(parents=True)
    (wf / "copilot-review.yml").write_text("name: x\n")
    return str(root)


def test_dump_then_check_roundtrip(synthetic_repo, capsys):
    assert contract_verb.main(["dump", "--root", synthetic_repo]) == 0
    assert contract_verb.main(["check", "--root", synthetic_repo]) == 0
    out = capsys.readouterr().out
    assert "is current" in out


def test_check_detects_drift_with_diff_and_advice(synthetic_repo, capsys):
    assert contract_verb.main(["dump", "--root", synthetic_repo]) == 0
    manifest = Path(synthetic_repo, contract.MANIFEST_RELPATH)
    manifest.write_text(manifest.read_text().replace("bin/check-gate", "bin/zzz-drifted"))
    assert contract_verb.main(["check", "--root", synthetic_repo]) == 1
    err = capsys.readouterr().err
    assert "bin/zzz-drifted" in err  # the diff names the drift
    assert "release-core admin contract dump" in err  # and the fix


def test_check_fails_when_manifest_is_missing(synthetic_repo, capsys):
    assert contract_verb.main(["check", "--root", synthetic_repo]) == 1
    assert "missing" in capsys.readouterr().err


def test_synthetic_manifest_classifies_by_the_sync_predicates(synthetic_repo):
    data = contract.build_manifest(synthetic_repo)
    assert data["untracked_mirrors"] == ["bin/check-gate"]
    assert data["tracked_real_files"]["workflow_copies"] == [".github/workflows/copilot-review.yml"]
    # install-release-core is bootstrap (quartet), never a mirror.
    assert "bin/install-release-core" not in data["untracked_mirrors"]


# ── Synthetic: the assumption lint ────────────────────────────────────────────

MANIFEST = {
    "managed_path_prefixes": [".release/", "bin/check", "lib/release_core/"],
    "untracked_mirrors": ["app-bin/smoke-hook.sh", ".editorconfig"],
}

VIOLATING_WF = """\
name: e2e
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run E2E tests
        run: bin/check-e2e
"""

COMPLIANT_WF = """\
name: e2e
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Arm the gate toolset
        uses: arthur-debert/release/.github/actions/arm-gate@v2
      - name: Run E2E tests
        run: bin/check-e2e
"""


def _write_wf(root: str, text: str, name: str = "wf.yml") -> None:
    wf_dir = Path(root, ".github", "workflows")
    wf_dir.mkdir(parents=True, exist_ok=True)
    (wf_dir / name).write_text(text)


def test_lint_detects_the_579_shape(tmp_path):
    """A job referencing bin/check-e2e with no materialize — the exact latent
    assumption #579 fixed — must FAIL."""
    root = str(tmp_path)
    _write_wf(root, VIOLATING_WF)
    violations = contract.lint_repo(root, MANIFEST)
    assert len(violations) == 1
    v = violations[0]
    assert (v.file, v.job, v.step) == (".github/workflows/wf.yml", "e2e", "Run E2E tests")
    assert v.matched == "bin/check-e2e"


def test_lint_passes_with_arm_gate_before_the_reference(tmp_path):
    root = str(tmp_path)
    _write_wf(root, COMPLIANT_WF)
    assert contract.lint_repo(root, MANIFEST) == []


def test_lint_requires_materialize_BEFORE_the_reference(tmp_path):
    """arm-gate AFTER the referencing step does not absolve it — order matters."""
    root = str(tmp_path)
    reordered = VIOLATING_WF + (
        "      - name: Arm the gate toolset (too late)\n"
        "        uses: arthur-debert/release/.github/actions/arm-gate@v2\n"
    )
    _write_wf(root, reordered)
    assert len(contract.lint_repo(root, MANIFEST)) == 1


def test_lint_accepts_release_core_init_run_line(tmp_path):
    root = str(tmp_path)
    wf = VIOLATING_WF.replace(
        "      - name: Run E2E tests\n",
        "      - name: Materialize\n        run: release-core init\n      - name: Run E2E tests\n",
    )
    _write_wf(root, wf)
    assert contract.lint_repo(root, MANIFEST) == []


def test_lint_treats_a_composite_action_as_one_job(tmp_path):
    root = str(tmp_path)
    action_dir = Path(root, ".github", "actions", "my-act")
    action_dir.mkdir(parents=True)
    (action_dir / "action.yml").write_text(
        "name: my-act\n"
        "runs:\n"
        "  using: composite\n"
        "  steps:\n"
        "    - name: use the gate\n"
        "      shell: bash\n"
        "      run: .release/lefthook.yml\n"
    )
    violations = contract.lint_repo(root, MANIFEST)
    assert len(violations) == 1
    assert violations[0].job == "(composite)"


def test_lint_scans_template_workflow_copies(tmp_path):
    root = str(tmp_path)
    wf_dir = Path(root, "templates", "mykind", ".github", "workflows")
    wf_dir.mkdir(parents=True)
    (wf_dir / "shipped.yml").write_text(VIOLATING_WF)
    violations = contract.lint_repo(root, MANIFEST)
    assert [v.file for v in violations] == ["templates/mykind/.github/workflows/shipped.yml"]


def test_lint_checkout_into_the_path_provides_it(tmp_path):
    """tauri-app.yml's convention: checking release's bin-internal out AT
    path: .release provides .release/ for later steps — not a violation."""
    root = str(tmp_path)
    _write_wf(
        root,
        "name: r\n"
        "on: [push]\n"
        "jobs:\n"
        "  release:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v6\n"
        "        with:\n"
        "          repository: arthur-debert/release\n"
        "          path: .release\n"
        "      - name: run helper\n"
        "        run: bash .release/bin-internal/create-github-release.sh\n",
    )
    assert contract.lint_repo(root, MANIFEST) == []


def test_lint_path_boundary_excludes_release_source_paths(tmp_path):
    """References to release's OWN source tree (templates/commons/lib/
    release_core/…) must not match the consumer-root lib/release_core/ pattern;
    full-line comments are stripped."""
    root = str(tmp_path)
    _write_wf(
        root,
        "name: t\n"
        "on: [push]\n"
        "jobs:\n"
        "  tests:\n"
        "    runs-on: ubuntu-latest\n"
        "    steps:\n"
        "      - uses: actions/checkout@v6\n"
        "      - name: pytest\n"
        "        run: |\n"
        "          # the consumer's bin/check is materialized by init\n"
        "          cd templates/commons/lib/release_core && pytest -q\n",
    )
    assert contract.lint_repo(root, MANIFEST) == []


def test_lint_catches_workspace_anchored_references(tmp_path):
    root = str(tmp_path)
    wf = VIOLATING_WF.replace("run: bin/check-e2e", 'run: "${GITHUB_WORKSPACE}/bin/check-e2e"')
    _write_wf(root, wf)
    violations = contract.lint_repo(root, MANIFEST)
    assert len(violations) == 1


def test_lint_scans_with_and_env_values(tmp_path):
    root = str(tmp_path)
    wf = VIOLATING_WF.replace(
        "      - name: Run E2E tests\n        run: bin/check-e2e\n",
        "      - name: upload\n"
        "        uses: actions/upload-artifact@v6\n"
        "        with:\n"
        "          path: .release/dist\n",
    )
    _write_wf(root, wf)
    assert len(contract.lint_repo(root, MANIFEST)) == 1


def test_lint_arm_gate_with_materialize_false_earns_no_credit(tmp_path):
    """arm-gate called with materialize:'false' (release's own ci.yml shape)
    does NOT compose the tree — a later managed-path reference still fails."""
    root = str(tmp_path)
    wf = COMPLIANT_WF.replace(
        "        uses: arthur-debert/release/.github/actions/arm-gate@v2\n",
        "        uses: arthur-debert/release/.github/actions/arm-gate@v2\n"
        "        with:\n"
        "          materialize: 'false'\n",
    )
    _write_wf(root, wf)
    violations = contract.lint_repo(root, MANIFEST)
    assert len(violations) == 1
    assert violations[0].matched == "bin/check-e2e"


def test_lint_arm_gate_toolset_false_still_materializes(tmp_path):
    """The #581 building block: arm-gate with toolset:'false' is materialize-only
    — it still composes the tree, so the job is compliant."""
    root = str(tmp_path)
    wf = COMPLIANT_WF.replace(
        "        uses: arthur-debert/release/.github/actions/arm-gate@v2\n",
        "        uses: arthur-debert/release/.github/actions/arm-gate@v2\n"
        "        with:\n"
        "          toolset: 'false'\n",
    )
    _write_wf(root, wf)
    assert contract.lint_repo(root, MANIFEST) == []


# ── The consumer-side workflow sweep (#581: init's seed-time tripwire) ────────

PATTERNS = [".release/", "bin/check", "lib/release_core/"]


def test_workflow_dir_sweep_flags_the_bad_job_with_exact_coordinates(tmp_path):
    root = str(tmp_path)
    _write_wf(root, VIOLATING_WF, name="e2e.yml")
    violations = contract.lint_workflow_dir(root, PATTERNS)
    assert len(violations) == 1
    v = violations[0]
    assert (v.file, v.job, v.step) == (".github/workflows/e2e.yml", "e2e", "Run E2E tests")
    assert v.matched == "bin/check-e2e"


def test_workflow_dir_sweep_silent_when_materialized_or_no_workflows(tmp_path):
    # No .github/workflows at all → silent.
    assert contract.lint_workflow_dir(str(tmp_path / "empty"), PATTERNS) == []
    # A materialized job → silent.
    root = str(tmp_path)
    _write_wf(root, COMPLIANT_WF)
    assert contract.lint_workflow_dir(root, PATTERNS) == []


def test_workflow_dir_sweep_skips_unparseable_file_without_silencing_rest(tmp_path):
    """One broken consumer workflow must not hide violations in the others —
    consumer-side resilience (init must warn from whatever it CAN parse)."""
    root = str(tmp_path)
    _write_wf(root, "{ this is : not [ yaml", name="broken.yml")
    _write_wf(root, VIOLATING_WF, name="e2e.yml")
    violations = contract.lint_workflow_dir(root, PATTERNS)
    assert [v.file for v in violations] == [".github/workflows/e2e.yml"]


def test_workflow_dir_sweep_only_scans_workflows(tmp_path):
    """The consumer sweep is .github/workflows/** ONLY — release-side surfaces
    (composite actions, templates/) belong to lint_repo, not the init tripwire."""
    root = str(tmp_path)
    action_dir = Path(root, ".github", "actions", "my-act")
    action_dir.mkdir(parents=True)
    (action_dir / "action.yml").write_text(
        "name: my-act\nruns:\n  using: composite\n  steps:\n"
        "    - name: use the gate\n      shell: bash\n      run: bin/check-e2e\n"
    )
    assert contract.lint_workflow_dir(root, PATTERNS) == []


# ── The shrink-only baseline ──────────────────────────────────────────────────


def test_baseline_grandfathers_listed_jobs_and_flags_stale_entries(tmp_path):
    root = str(tmp_path)
    _write_wf(root, VIOLATING_WF)
    violations = contract.lint_repo(root, MANIFEST)
    baseline = [
        {"file": ".github/workflows/wf.yml", "job": "e2e", "reason": "known"},
        {"file": ".github/workflows/gone.yml", "job": "old", "reason": "drained"},
    ]
    failing, grandfathered, stale = contract.apply_baseline(violations, baseline)
    assert failing == []
    assert len(grandfathered) == 1
    assert [e["job"] for e in stale] == ["old"]  # the ratchet: must be deleted


def test_lint_verb_fails_on_new_violation_and_stale_entry(synthetic_repo, capsys):
    assert contract_verb.main(["dump", "--root", synthetic_repo]) == 0
    _write_wf(synthetic_repo, VIOLATING_WF)
    assert contract_verb.main(["lint", "--root", synthetic_repo]) == 1
    err = capsys.readouterr().err
    assert ".github/workflows/wf.yml -> e2e -> Run E2E tests" in err

    # Baseline the job → lint passes; then fix the job → the stale entry fails.
    Path(synthetic_repo, contract.BASELINE_RELPATH).write_text(
        'known_stale_jobs:\n  - {file: ".github/workflows/wf.yml", job: "e2e", reason: "x"}\n'
    )
    assert contract_verb.main(["lint", "--root", synthetic_repo]) == 0
    _write_wf(synthetic_repo, COMPLIANT_WF)
    assert contract_verb.main(["lint", "--root", synthetic_repo]) == 1
    assert "STALE baseline entry" in capsys.readouterr().err


# ── Verb plumbing ─────────────────────────────────────────────────────────────


def test_verb_usage_errors():
    assert contract_verb.main([]) == 64
    assert contract_verb.main(["frobnicate"]) == 64
    assert contract_verb.main(["check", "--bogus"]) == 64


def test_verb_help(capsys):
    assert contract_verb.main(["--help"]) == 0
    assert "dump" in capsys.readouterr().out


def test_resolve_root_rejects_a_non_release_tree(tmp_path):
    assert contract_verb.main(["check", "--root", str(tmp_path)]) == 1


def test_wrappers_forward_to_subcommands(synthetic_repo):
    assert contract_verb.dump_main(["--root", synthetic_repo]) == 0
    assert contract_verb.check_main(["--root", synthetic_repo]) == 0
    assert contract_verb.lint_main(["--root", synthetic_repo]) == 0


def test_baseline_rejects_malformed_entries(tmp_path):
    root = tmp_path / "r"
    (root / "docs" / "references").mkdir(parents=True)
    (root / contract.BASELINE_RELPATH).write_text("known_stale_jobs:\n  - {job: only-job}\n")
    with pytest.raises(contract.ContractError):
        contract.load_baseline(str(root))


def _has_executable_bit(path: str) -> bool:
    return bool(os.stat(path).st_mode & stat.S_IXUSR)


def test_gate_wrappers_exist_and_are_executable():
    wrappers = (
        "bin-internal/check-consumer-contract.sh",
        "bin-internal/lint-consumer-contract.sh",
    )
    for rel in wrappers:
        full = os.path.join(REPO_ROOT, rel)
        assert os.path.isfile(full), rel
        assert _has_executable_bit(full), rel
