require "download_strategy"

# Inlined private-release downloader. Reads HOMEBREW_GITHUB_API_TOKEN
# and translates the public release URL into the authenticated assets
# API endpoint. Without this, brew install 404s on private-repo
# releases. Generated by arthur-debert/release; do not edit by hand.
class GitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  require "utils/github"

  def initialize(url, name, version, **meta)
    super
    parse_url_pattern
    set_github_token
  end

  def parse_url_pattern
    url_pattern = %r{https://github.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(\S+)}
    raise CurlDownloadStrategyError, "Invalid url pattern for GitHub Release." unless @url =~ url_pattern
    _, @owner, @repo, @tag, @filename = *@url.match(url_pattern).to_a
  end

  def set_github_token
    @github_token = ENV["HOMEBREW_GITHUB_API_TOKEN"]
    raise CurlDownloadStrategyError, "HOMEBREW_GITHUB_API_TOKEN is required for private-repo brew installs." unless @github_token
  end

  def asset_id
    @asset_id ||= begin
      release_url = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}"
      release = GitHub.open_api(release_url)
      asset = release["assets"]&.find { |a| a["name"] == @filename }
      raise CurlDownloadStrategyError, "Asset #{@filename} not found in release #{@tag}." unless asset
      asset["id"]
    end
  end

  def _fetch(url:, resolved_url:, timeout:)
    api_url = "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}"
    curl_download api_url,
                  "--header", "Accept: application/octet-stream",
                  "--header", "Authorization: Bearer #{@github_token}",
                  to: temporary_path, timeout: timeout
  end
end
